apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: master-delivery
data:
  POSTGRES_DB: masterdelivery
  POSTGRES_USER: masterdelivery
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: master-delivery
type: Opaque
data:
  POSTGRES_PASSWORD: bWFzdGVyZGVsaXZlcnk= # base64 encoded 'masterdelivery'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: master-delivery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: master-delivery
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: master-delivery
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP 