global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'master-delivery-services'
    static_configs:
      - targets:
        - 'auth-service:3000'
        - 'order-service:3000'
        - 'payment-service:3000'
        - 'restaurant-service:3000'
        - 'delivery-service:3000'
        - 'notification-service:3000'
        - 'geolocation-service:3000' 